Include Nico changes
Signed-off-by: Thomas Steenbergen <opensource@steenbe.nl>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,3 +1,4 @@
+---
 # Copyright (C) 2022 The ORT Project Authors
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -30,12 +31,12 @@ inputs:
       Set to 'true' only if dynamic dependency versions are allowed (note version ranges specified for dependencies may cause unstable results).
       This field applies only to package managers that support lock files, e.g. NPM.
     required: false
-    default: true
+    default: 'true'
   create-source-code-bundle:
     description: |
       Set to 'true' only if an archive of source code for configured packages is to be created.
     required: false
-    default: false
+    default: 'false'
   docker-cli-args:
     description: |
       List of arguments to pass to Docker CLI.
@@ -122,6 +123,7 @@ inputs:
       Project version number or release name (use the version from package metadata, not VCS revision).
       By default, the Git short SHA is used.
     required: false
+    default: ''
 
 runs:
   using: 'composite'
@@ -167,15 +169,17 @@ runs:
         ORT_DOCKER_CLI_ARGS: ${{ inputs.docker-cli-args }}
         ORT_DOCKER_IMAGE: ${{ inputs.image }}
         ORT_LOG_LEVEL: ${{ inputs.log-level }}
-        ORT_REPO_CONFIG_FILE:  ${{ inputs.ort-repo-config-file}}
+        ORT_REPO_CONFIG_FILE: ${{ inputs.ort-repo-config-file}}
         ORT_RUN_COMMANDS: ${{ inputs.run }}
+        ORT_SW_NAME: ${{ inputs.sw-name }}
+        ORT_SW_VERSION: ${{ inputs.sw-version }}
       run: |
         echo -e "\e[1;33m Initializing ORT in GitHub workspace... "
-
         [[ -d $HOME/.ort/cache/ ]] || mkdir -p $HOME/.ort/cache/
         [[ -d $HOME/.ort/config/ ]] || mkdir -p $HOME/.ort/config/
         [[ -d $HOME/.ort/ort-results/ ]] || mkdir $HOME/.ort/ort-results/
         [[ -d $HOME/.ort/scanner/archive/ ]] || mkdir -p $HOME/.ort/scanner/archive/; chmod -R aug+w ${HOME}/.ort/
+        [[ -d $HOME/.gradle/ ]] || mkdir -p $HOME/.gradle/; chmod -R aug+w ${HOME}/.gradle/
         chmod -R aug+w ${{ github.workspace }}/
         export ORT_CONFIG_DIR="${HOME}/.ort/config"
         [[ -z "$(ls -A ${ORT_CONFIG_DIR})" ]] && export ORT_CONFIG_DIR_IS_EMPTY=true || export ORT_CONFIG_DIR_IS_EMPTY=false
@@ -188,11 +192,9 @@ runs:
         export ORT_RESULTS_HTML_REPORT_FILE="${ORT_RESULTS_DIR}/ort-results/scan-report.html"
         export ORT_RESULTS_SCANNER_FILE="${ORT_RESULTS_DIR}/scanner-result.json"
         export ORT_RESULTS_WEB_APP_FILE="${ORT_RESULTS_DIR}/scan-report-web-app.html"
-
+        [[ -n "${ORT_SW_NAME}" ]] && export ORT_RESULTS_NAME="ort-results-${ORT_SW_NAME}" || export ORT_RESULTS_NAME="ort-results"
+        [[ -n "${ORT_SW_VERSION}" ]] && export ORT_RESULTS_NAME="${ORT_RESULTS_NAME}-${ORT_SW_VERSION}"
         printenv >> "$GITHUB_ENV"
-    # - name: Print all environment variables
-    #   shell: bash
-    #   run: printenv
     - name: Shallow clone ort-config repository
       shell: bash
       env:
@@ -240,110 +242,100 @@ runs:
         ORT_ALLOW_DYNAMIC_VERSIONS: ${{ inputs.allow-dynamic-versions }}
         ORT_PROJECT_DIR: ${{ inputs.project-dir }}
       run: |
-          echo -e "\e[1;33m Running ORT Analyzer... "
-
-          if [[ ! -z "${ORT_ALLOW_DYNAMIC_VERSIONS}" ]]; then
-            ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_ALLOW_DYNAMIC_VERSIONS=${ORT_ALLOW_DYNAMIC_VERSIONS}"
-          fi
-
-          if [[ ! -z "${ORT_CONFIG_VCS_URL}" ]]; then
-            ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_CONFIG_VCS_URL=${ORT_CONFIG_VCS_URL}"
-          fi
-
-          if [[ ! -z "${ORT_CONFIG_VCS_REVISION}" ]]; then
-            ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_CONFIG_VCS_REVISION=${ORT_CONFIG_VCS_REVISION}"
-          fi
-
-          if [[ ! -z "${ORT_REPO_CONFIG_FILE}" ]]; then
-            ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} --repository-configuration-file=${ORT_REPO_CONFIG_FILE} -l ORT_YML_FILE=${ORT_REPO_CONFIG_FILE}" 
-          fi
-
-          echo "ORT_CLI_ANALYZE_ARGS: ${ORT_CLI_ANALYZE_ARGS}"
-
-          docker run \
-          --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
-          --mount type=bind,source=/etc/group,target=/etc/group,readonly \
-          --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
-          --mount type=bind,source=$HOME,target=$HOME \
-          -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
-          -e ORT_DATA_DIR="${HOME}/.ort/" \
-          $ORT_DOCKER_CLI_ARGS \
-          $ORT_DOCKER_IMAGE \
-          --$ORT_LOG_LEVEL \
-          -P ort.analyzer.allowDynamicVersions=${ORT_ALLOW_DYNAMIC_VERSIONS} \
-          $ORT_CLI_ARGS \
-          analyze \
-          -i ${{ github.workspace }}/$ORT_PROJECT_DIR \
-          -o $ORT_RESULTS_DIR \
-          -f JSON \
-          ${ORT_CLI_ANALYZE_ARGS}
-
-          [[ -f $ORT_RESULTS_ANALYZER_FILE ]] && \
-            ln -frs $ORT_RESULTS_ANALYZER_FILE $ORT_RESULTS_CURRENT_FILE || \
-            echo -e "\e[1;31m $ORT_RESULTS_ANALYZER_FILE missing."
+        echo -e "\e[1;33m Running ORT Analyzer... "
+        if [[ ! -z "${ORT_ALLOW_DYNAMIC_VERSIONS}" ]]; then
+          ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_ALLOW_DYNAMIC_VERSIONS=${ORT_ALLOW_DYNAMIC_VERSIONS}"
+        fi
+        if [[ ! -z "${ORT_CONFIG_VCS_URL}" ]]; then
+          ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_CONFIG_VCS_URL=${ORT_CONFIG_VCS_URL}"
+        fi
+        if [[ ! -z "${ORT_CONFIG_VCS_REVISION}" ]]; then
+          ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} -l ORT_CONFIG_VCS_REVISION=${ORT_CONFIG_VCS_REVISION}"
+        fi
+        if [[ ! -z "${ORT_REPO_CONFIG_FILE}" ]]; then
+          ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} --repository-configuration-file=${ORT_REPO_CONFIG_FILE} -l ORT_YML_FILE=${ORT_REPO_CONFIG_FILE}"
+        fi
+        echo "ORT_CLI_ANALYZE_ARGS: ${ORT_CLI_ANALYZE_ARGS}"
+        docker run \
+        --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
+        --mount type=bind,source=/etc/group,target=/etc/group,readonly \
+        --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
+        --mount type=bind,source=$HOME,target=$HOME \
+        -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
+        -e ORT_DATA_DIR="${HOME}/.ort/" \
+        -e GRADLE_USER_HOME="${HOME}/.gradle" \
+        $ORT_DOCKER_CLI_ARGS \
+        $ORT_DOCKER_IMAGE \
+        --$ORT_LOG_LEVEL \
+        -P ort.analyzer.allowDynamicVersions=${ORT_ALLOW_DYNAMIC_VERSIONS} \
+        $ORT_CLI_ARGS \
+        analyze \
+        -i ${{ github.workspace }}/$ORT_PROJECT_DIR \
+        -o $ORT_RESULTS_DIR \
+        -f JSON \
+        ${ORT_CLI_ANALYZE_ARGS}
+        [[ -f $ORT_RESULTS_ANALYZER_FILE ]] && \
+          ln -frs $ORT_RESULTS_ANALYZER_FILE $ORT_RESULTS_CURRENT_FILE || \
+          echo -e "\e[1;31m $ORT_RESULTS_ANALYZER_FILE missing."
     - name: ORT Scanner
       id: scanner
       shell: bash
       if: contains(inputs.run, 'scanner')
       run: |
-          echo -e "\e[1;33m Running ORT Scanner... "
-
-          curl https://raw.githubusercontent.com/oss-review-toolkit/orthw/main/examples/npm-mime-types-2.1.26-scan-result.json > $ORT_RESULTS_SCANNER_FILE 
-
-          # docker run \
-          # --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
-          # --mount type=bind,source=/etc/group,target=/etc/group,readonly \
-          # --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
-          # --mount type=bind,source=$HOME,target=$HOME \
-          # -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
-          # -e ORT_DATA_DIR="${HOME}/.ort/" \
-          # $ORT_DOCKER_CLI_ARGS \
-          # $ORT_DOCKER_IMAGE \
-          # --$ORT_LOG_LEVEL \
-          # $ORT_CLI_ARGS \
-          # scan \
-          # -i $ORT_RESULTS_CURRENT_FILE \
-          # -o $ORT_RESULTS_DIR \
-          # -f JSON \
-          # ${ORT_CLI_EVALUATE_ARGS}
-
-          [[ -f $ORT_RESULTS_SCANNER_FILE ]] && \
-            ln -frs $ORT_RESULTS_SCANNER_FILE $ORT_RESULTS_CURRENT_FILE || \
-            echo -e "\e[1;31m $ORT_RESULTS_SCANNER_FILE missing."
+        echo -e "\e[1;33m Running ORT Scanner... "
+        curl https://raw.githubusercontent.com/oss-review-toolkit/orthw/main/examples/npm-mime-types-2.1.26-scan-result.json > $ORT_RESULTS_SCANNER_FILE
+        # docker run \
+        # --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
+        # --mount type=bind,source=/etc/group,target=/etc/group,readonly \
+        # --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
+        # --mount type=bind,source=$HOME,target=$HOME \
+        # -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
+        # -e ORT_DATA_DIR="${HOME}/.ort/" \
+        # -e GRADLE_USER_HOME="${HOME}/.gradle" \
+        # $ORT_DOCKER_CLI_ARGS \
+        # $ORT_DOCKER_IMAGE \
+        # --$ORT_LOG_LEVEL \
+        # $ORT_CLI_ARGS \
+        # scan \
+        # -i $ORT_RESULTS_CURRENT_FILE \
+        # -o $ORT_RESULTS_DIR \
+        # -f JSON \
+        # ${ORT_CLI_EVALUATE_ARGS}
+        [[ -f $ORT_RESULTS_SCANNER_FILE ]] && \
+          ln -frs $ORT_RESULTS_SCANNER_FILE $ORT_RESULTS_CURRENT_FILE || \
+          echo -e "\e[1;31m $ORT_RESULTS_SCANNER_FILE missing."
     - name: ORT Evaluator
       id: evaluator
       shell: bash
       if: contains(inputs.run, 'evaluator')
       run: |
-          echo -e "\e[1;33m Running ORT Evaluator... "
-
-          docker run \
-          --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
-          --mount type=bind,source=/etc/group,target=/etc/group,readonly \
-          --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
-          --mount type=bind,source=$HOME,target=$HOME \
-          -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
-          -e ORT_DATA_DIR="${HOME}/.ort/" \
-          $ORT_DOCKER_CLI_ARGS \
-          $ORT_DOCKER_IMAGE \
-          --$ORT_LOG_LEVEL \
-          $ORT_CLI_ARGS \
-          evaluate \
-          -i $ORT_RESULTS_CURRENT_FILE \
-          -o $ORT_RESULTS_DIR \
-          -f JSON \
-          ${ORT_CLI_EVALUATE_ARGS}
-
-          [[ -f $ORT_RESULTS_EVALUATOR_FILE ]] && \
-            ln -frs $ORT_RESULTS_EVALUATOR_FILE $ORT_RESULTS_CURRENT_FILE || \
-            echo -e "\e[1;31m $ORT_RESULTS_EVALUATOR_FILE missing."
-
-          EXIT_CODE=$?
-          if [[ $EXIT_CODE -ge 2 ]]; then
-              echo "ORT_EVALUATOR_EXIT_CODE=${EXIT_CODE}" >> "$GITHUB_ENV"
-              EXIT_CODE=0
-          fi
-          exit $EXIT_CODE
+        echo -e "\e[1;33m Running ORT Evaluator... "
+        docker run \
+        --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
+        --mount type=bind,source=/etc/group,target=/etc/group,readonly \
+        --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
+        --mount type=bind,source=$HOME,target=$HOME \
+        -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
+        -e ORT_DATA_DIR="${HOME}/.ort/" \
+        -e GRADLE_USER_HOME="${HOME}/.gradle" \
+        $ORT_DOCKER_CLI_ARGS \
+        $ORT_DOCKER_IMAGE \
+        --$ORT_LOG_LEVEL \
+        $ORT_CLI_ARGS \
+        evaluate \
+        -i $ORT_RESULTS_CURRENT_FILE \
+        -o $ORT_RESULTS_DIR \
+        -f JSON \
+        ${ORT_CLI_EVALUATE_ARGS}
+        [[ -f $ORT_RESULTS_EVALUATOR_FILE ]] && \
+          ln -frs $ORT_RESULTS_EVALUATOR_FILE $ORT_RESULTS_CURRENT_FILE || \
+          echo -e "\e[1;31m $ORT_RESULTS_EVALUATOR_FILE missing."
+        EXIT_CODE=$?
+        if [[ $EXIT_CODE -ge 2 ]]; then
+            echo "ORT_EVALUATOR_EXIT_CODE=${EXIT_CODE}" >> "$GITHUB_ENV"
+            EXIT_CODE=0
+        fi
+        exit $EXIT_CODE
     - name: ORT Advisor
       id: advisor
       shell: bash
@@ -351,29 +343,28 @@ runs:
       env:
         ORT_ADVISORS: ${{ inputs.advisors }}
       run: |
-          echo -e "\e[1;33m Running ORT Advisor... "
-
-          docker run \
-          --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
-          --mount type=bind,source=/etc/group,target=/etc/group,readonly \
-          --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
-          --mount type=bind,source=$HOME,target=$HOME \
-          -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
-          -e ORT_DATA_DIR="${HOME}/.ort/" \
-          $ORT_DOCKER_CLI_ARGS \
-          $ORT_DOCKER_IMAGE \
-          --$ORT_LOG_LEVEL \
-          $ORT_CLI_ARGS \
-          advise \
-          -i $ORT_RESULTS_CURRENT_FILE \
-          -o $ORT_RESULTS_DIR \
-          -a $ORT_ADVISORS \
-          -f JSON \
-          ${ORT_CLI_ADVISE_ARGS}
-
-          [[ -f $ORT_RESULTS_ADVISOR_FILE ]] && \
-            ln -frs $ORT_RESULTS_ADVISOR_FILE $ORT_RESULTS_CURRENT_FILE || \
-            echo -e "\e[1;31m $ORT_RESULTS_ADVISOR_FILE missing."
+        echo -e "\e[1;33m Running ORT Advisor... "
+        docker run \
+        --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
+        --mount type=bind,source=/etc/group,target=/etc/group,readonly \
+        --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
+        --mount type=bind,source=$HOME,target=$HOME \
+        -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
+        -e ORT_DATA_DIR="${HOME}/.ort/" \
+        -e GRADLE_USER_HOME="${HOME}/.gradle" \
+        $ORT_DOCKER_CLI_ARGS \
+        $ORT_DOCKER_IMAGE \
+        --$ORT_LOG_LEVEL \
+        $ORT_CLI_ARGS \
+        advise \
+        -i $ORT_RESULTS_CURRENT_FILE \
+        -o $ORT_RESULTS_DIR \
+        -a $ORT_ADVISORS \
+        -f JSON \
+        ${ORT_CLI_ADVISE_ARGS}
+        [[ -f $ORT_RESULTS_ADVISOR_FILE ]] && \
+          ln -frs $ORT_RESULTS_ADVISOR_FILE $ORT_RESULTS_CURRENT_FILE || \
+          echo -e "\e[1;31m $ORT_RESULTS_ADVISOR_FILE missing."
     - name: ORT Reporter
       id: reporter
       shell: bash
@@ -382,31 +373,29 @@ runs:
         SW_NAME: ${{ inputs.sw-name }}
       if: contains(inputs.run, 'reporter')
       run: |
-          echo -e "\e[1;33m Running ORT Reporter... "
-
-          if [[ ! -z "${ORT_REPO_CONFIG_FILE}" ]]; then
-            ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} --repository-configuration-file=${ORT_REPO_CONFIG_FILE} -l ORT_YML_FILE=${ORT_REPO_CONFIG_FILE}" 
-          fi
-
-          docker run \
-          --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
-          --mount type=bind,source=/etc/group,target=/etc/group,readonly \
-          --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
-          --mount type=bind,source=$HOME,target=$HOME \
-          -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
-          -e ORT_DATA_DIR="${HOME}/.ort/" \
-          $ORT_DOCKER_CLI_ARGS \
-          $ORT_DOCKER_IMAGE \
-          --$ORT_LOG_LEVEL \
-          $ORT_CLI_ARGS \
-          report \
-          -i $ORT_RESULTS_CURRENT_FILE \
-          -o $ORT_RESULTS_DIR \
-          -f $ORT_REPORT_FORMATS \
-          -O SpdxDocument=document.name="${SW_NAME}" \
-          ${ORT_CLI_REPORT_ARGS}
-
-          ls -all $ORT_RESULTS_DIR
+        echo -e "\e[1;33m Running ORT Reporter... "
+        if [[ ! -z "${ORT_REPO_CONFIG_FILE}" ]]; then
+          ORT_CLI_ANALYZE_ARGS="${ORT_CLI_ANALYZE_ARGS} --repository-configuration-file=${ORT_REPO_CONFIG_FILE} -l ORT_YML_FILE=${ORT_REPO_CONFIG_FILE}"
+        fi
+        docker run \
+        --mount type=bind,source=${{ github.workspace }}/,target=/workspace \
+        --mount type=bind,source=/etc/group,target=/etc/group,readonly \
+        --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
+        --mount type=bind,source=$HOME,target=$HOME \
+        -e JDK_JAVA_OPTIONS="--illegal-access=warn -Xmx5120m" \
+        -e ORT_DATA_DIR="${HOME}/.ort/" \
+        -e GRADLE_USER_HOME="${HOME}/.gradle" \
+        $ORT_DOCKER_CLI_ARGS \
+        $ORT_DOCKER_IMAGE \
+        --$ORT_LOG_LEVEL \
+        $ORT_CLI_ARGS \
+        report \
+        -i $ORT_RESULTS_CURRENT_FILE \
+        -o $ORT_RESULTS_DIR \
+        -f $ORT_REPORT_FORMATS \
+        -O SpdxDocument=document.name="${SW_NAME}" \
+        ${ORT_CLI_REPORT_ARGS}
+        ls -all $ORT_RESULTS_DIR
     - name: Remove current-result.yml file if present
       shell: bash
       run: |
@@ -417,6 +406,6 @@ runs:
       uses: actions/upload-artifact@v3
       if: contains(inputs.run, 'upload-results')
       with:
-        name: ort-results
+        name: ${{ env.ORT_RESULTS_NAME }}
         path: ${{ env.HOME }}/.ort/ort-results/
         if-no-files-found: warn
